# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23fdbd2d81dcd773c4cb5c7943771d2d9f7fab9020bc90a232d820c65fbd140700707210d0411516e1c17cb534d0461b014577b11fb0c56e6d22eda06223e8e2

test:
  secret_key_base: 228576cb4c9dc2cebff93356196e3007cac1cb510a6f57c0ab69bc10d9f24d35bf77240dbfaa7cbc5d286bf9504328c88b2f4ec33a0ebbaf0a124666422ade39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
